version: '3.8'

services:
  db:
    image: mysql
    container_name: mysql_bookingapp
    environment:
      - MYSQL_ROOT_HOST=${DB_HOST} 
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    restart: on-failure
    # networks:
    #   - bookingapp_network
  app:
    container_name: bookingapp_api
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    # networks:
    #   - bookingapp_network
    command: go run ./main.go


# volumes:
#   api:
#   database_mysql:
  

# networks:
#   bookingapp_network:
#     name: bookingapp_network



